export default function userList() {
    return {
        "items": [
            {
                "badge_counts": {
                    "bronze": 8616,
                    "silver": 8233,
                    "gold": 720
                },
                "account_id": 11683,
                "is_employee": false,
                "last_modified_date": 1572136518,
                "last_access_date": 1572080344,
                "reputation_change_year": 62299,
                "reputation_change_quarter": 5432,
                "reputation_change_month": 5432,
                "reputation_change_week": 70,
                "reputation_change_day": 70,
                "reputation": 1139926,
                "creation_date": 1222430705,
                "user_type": "registered",
                "user_id": 22656,
                "accept_rate": 86,
                "location": "Reading, United Kingdom",
                "website_url": "http://csharpindepth.com",
                "link": "https://stackoverflow.com/users/22656/jon-skeet",
                "profile_image": "https://www.gravatar.com/avatar/6d8ebb117e8d83d74ea95fbdd0f87e13?s=128&d=identicon&r=PG",
                "display_name": "Jon Skeet"
            },
            {
                "badge_counts": {
                    "bronze": 3530,
                    "silver": 2931,
                    "gold": 332
                },
                "account_id": 4243,
                "is_employee": false,
                "last_modified_date": 1571432708,
                "last_access_date": 1572141617,
                "reputation_change_year": 70963,
                "reputation_change_quarter": 6347,
                "reputation_change_month": 6347,
                "reputation_change_week": 125,
                "reputation_change_day": 125,
                "reputation": 901609,
                "creation_date": 1221344553,
                "user_type": "registered",
                "user_id": 6309,
                "accept_rate": 100,
                "location": "France",
                "website_url": "http://careers.stackoverflow.com/vonc",
                "link": "https://stackoverflow.com/users/6309/vonc",
                "profile_image": "https://www.gravatar.com/avatar/7aa22372b695ed2b26052c340f9097eb?s=128&d=identicon&r=PG",
                "display_name": "VonC"
            },
            {
                "badge_counts": {
                    "bronze": 3301,
                    "silver": 3272,
                    "gold": 314
                },
                "account_id": 52822,
                "is_employee": false,
                "last_modified_date": 1571837101,
                "last_access_date": 1572048613,
                "reputation_change_year": 52568,
                "reputation_change_quarter": 4680,
                "reputation_change_month": 4680,
                "reputation_change_week": 20,
                "reputation_change_day": 20,
                "reputation": 894110,
                "creation_date": 1250527322,
                "user_type": "registered",
                "user_id": 157882,
                "accept_rate": 93,
                "location": "Willemstad, Cura&#231;ao",
                "website_url": "http://balusc.omnifaces.org",
                "link": "https://stackoverflow.com/users/157882/balusc",
                "profile_image": "https://www.gravatar.com/avatar/89927e2f4bde24991649b353a37678b9?s=128&d=identicon&r=PG",
                "display_name": "BalusC"
            },
            {
                "badge_counts": {
                    "bronze": 2795,
                    "silver": 3084,
                    "gold": 234
                },
                "account_id": 14332,
                "is_employee": false,
                "last_modified_date": 1571090710,
                "last_access_date": 1572017435,
                "reputation_change_year": 47179,
                "reputation_change_quarter": 3978,
                "reputation_change_month": 3978,
                "reputation_change_week": 10,
                "reputation_change_day": 10,
                "reputation": 882096,
                "creation_date": 1224432467,
                "user_type": "registered",
                "user_id": 29407,
                "accept_rate": 86,
                "location": "Sofia, Bulgaria",
                "website_url": "http://stackoverflow.com/search?q=user%3a29407&tab=newest",
                "link": "https://stackoverflow.com/users/29407/darin-dimitrov",
                "profile_image": "https://www.gravatar.com/avatar/e3a181e9cdd4757a8b416d93878770c5?s=128&d=identicon&r=PG",
                "display_name": "Darin Dimitrov"
            },
            {
                "badge_counts": {
                    "bronze": 462,
                    "silver": 362,
                    "gold": 39
                },
                "account_id": 1165580,
                "is_employee": false,
                "last_modified_date": 1572095109,
                "last_access_date": 1572137499,
                "reputation_change_year": 114130,
                "reputation_change_quarter": 10327,
                "reputation_change_month": 10327,
                "reputation_change_week": 130,
                "reputation_change_day": 130,
                "reputation": 872491,
                "creation_date": 1326311637,
                "user_type": "registered",
                "user_id": 1144035,
                "location": "New York, United States",
                "website_url": "http://www.data-miners.com",
                "link": "https://stackoverflow.com/users/1144035/gordon-linoff",
                "profile_image": "https://www.gravatar.com/avatar/e514b017977ebf742a418cac697d8996?s=128&d=identicon&r=PG",
                "display_name": "Gordon Linoff"
            },
            {
                "badge_counts": {
                    "bronze": 2632,
                    "silver": 2235,
                    "gold": 214
                },
                "account_id": 11975,
                "is_employee": true,
                "last_modified_date": 1572155703,
                "last_access_date": 1572083945,
                "reputation_change_year": 51552,
                "reputation_change_quarter": 4814,
                "reputation_change_month": 4814,
                "reputation_change_week": 7,
                "reputation_change_day": 7,
                "reputation": 828608,
                "creation_date": 1222667162,
                "user_type": "moderator",
                "user_id": 23354,
                "accept_rate": 100,
                "location": "Forest of Dean, United Kingdom",
                "website_url": "http://blog.marcgravell.com",
                "link": "https://stackoverflow.com/users/23354/marc-gravell",
                "profile_image": "https://i.stack.imgur.com/3vbu5.jpg?s=128&g=1",
                "display_name": "Marc Gravell"
            },
            {
                "badge_counts": {
                    "bronze": 2201,
                    "silver": 1414,
                    "gold": 114
                },
                "account_id": 9266,
                "is_employee": false,
                "last_modified_date": 1571926805,
                "last_access_date": 1572158231,
                "reputation_change_year": 34181,
                "reputation_change_quarter": 2906,
                "reputation_change_month": 2906,
                "reputation_change_week": 8,
                "reputation_change_day": 8,
                "reputation": 818265,
                "creation_date": 1221698729,
                "user_type": "registered",
                "user_id": 17034,
                "location": "Madison, WI",
                "website_url": "",
                "link": "https://stackoverflow.com/users/17034/hans-passant",
                "profile_image": "https://i.stack.imgur.com/Cii6b.png?s=128&g=1",
                "display_name": "Hans Passant"
            },
            {
                "badge_counts": {
                    "bronze": 2024,
                    "silver": 1983,
                    "gold": 147
                },
                "account_id": 39846,
                "is_employee": false,
                "last_modified_date": 1571810702,
                "last_access_date": 1572131148,
                "reputation_change_year": 53135,
                "reputation_change_quarter": 3958,
                "reputation_change_month": 3958,
                "reputation_change_week": 10,
                "reputation_change_day": 10,
                "reputation": 817111,
                "creation_date": 1243786808,
                "user_type": "registered",
                "user_id": 115145,
                "accept_rate": 84,
                "location": "Pennsylvania, United States",
                "website_url": "https://commonsware.com",
                "link": "https://stackoverflow.com/users/115145/commonsware",
                "profile_image": "https://i.stack.imgur.com/wDnd8.png?s=128&g=1",
                "display_name": "CommonsWare"
            },
            {
                "badge_counts": {
                    "bronze": 2516,
                    "silver": 2808,
                    "gold": 169
                },
                "account_id": 35417,
                "is_employee": false,
                "last_modified_date": 1572096920,
                "last_access_date": 1572143835,
                "reputation_change_year": 68435,
                "reputation_change_quarter": 5604,
                "reputation_change_month": 5604,
                "reputation_change_week": 60,
                "reputation_change_day": 60,
                "reputation": 768777,
                "creation_date": 1241362437,
                "user_type": "moderator",
                "user_id": 100297,
                "location": "Cambridge, UK",
                "website_url": "http://www.zopatista.com/",
                "link": "https://stackoverflow.com/users/100297/martijn-pieters",
                "profile_image": "https://www.gravatar.com/avatar/24780fb6df85a943c7aea0402c843737?s=128&d=identicon&r=PG",
                "display_name": "Martijn Pieters"
            },
            {
                "badge_counts": {
                    "bronze": 1413,
                    "silver": 1354,
                    "gold": 136
                },
                "account_id": 52616,
                "is_employee": false,
                "last_modified_date": 1572113102,
                "last_access_date": 1572112478,
                "reputation_change_year": 68361,
                "reputation_change_quarter": 5950,
                "reputation_change_month": 5950,
                "reputation_change_week": 0,
                "reputation_change_day": 0,
                "reputation": 745809,
                "creation_date": 1250420422,
                "user_type": "registered",
                "user_id": 157247,
                "accept_rate": 91,
                "location": "United Kingdom",
                "website_url": "http://www.farsightsoftware.com",
                "link": "https://stackoverflow.com/users/157247/t-j-crowder",
                "profile_image": "https://www.gravatar.com/avatar/ca3e484c121268e4c8302616b2395eb9?s=128&d=identicon&r=PG",
                "display_name": "T.J. Crowder"
            },
            {
                "badge_counts": {
                    "bronze": 1819,
                    "silver": 1703,
                    "gold": 147
                },
                "account_id": 15988,
                "is_employee": false,
                "last_modified_date": 1571158814,
                "last_access_date": 1570732591,
                "reputation_change_year": 44836,
                "reputation_change_quarter": 3683,
                "reputation_change_month": 3683,
                "reputation_change_week": 10,
                "reputation_change_day": 10,
                "reputation": 722580,
                "creation_date": 1225829805,
                "user_type": "registered",
                "user_id": 34397,
                "accept_rate": 87,
                "location": "New Jersey",
                "website_url": "https://SLaks.net",
                "link": "https://stackoverflow.com/users/34397/slaks",
                "profile_image": "https://www.gravatar.com/avatar/7deca8ec973c3c0875e9a36e1e3e2c44?s=128&d=identicon&r=PG",
                "display_name": "SLaks"
            },
            {
                "badge_counts": {
                    "bronze": 1187,
                    "silver": 1042,
                    "gold": 157
                },
                "account_id": 680,
                "is_employee": false,
                "last_modified_date": 1571763912,
                "last_access_date": 1572079560,
                "reputation_change_year": 52629,
                "reputation_change_quarter": 4443,
                "reputation_change_month": 4443,
                "reputation_change_week": 50,
                "reputation_change_day": 50,
                "reputation": 716317,
                "creation_date": 1218356820,
                "user_type": "registered",
                "user_id": 893,
                "accept_rate": 84,
                "location": "Christchurch, New Zealand",
                "website_url": "http://hewgill.com",
                "link": "https://stackoverflow.com/users/893/greg-hewgill",
                "profile_image": "https://www.gravatar.com/avatar/747ffa5da3538e66840ebc0548b8fd58?s=128&d=identicon&r=PG",
                "display_name": "Greg Hewgill"
            },
            {
                "badge_counts": {
                    "bronze": 1095,
                    "silver": 944,
                    "gold": 82
                },
                "account_id": 10162,
                "is_employee": false,
                "last_modified_date": 1572122107,
                "last_access_date": 1572101400,
                "reputation_change_year": 54437,
                "reputation_change_quarter": 3980,
                "reputation_change_month": 3980,
                "reputation_change_week": 30,
                "reputation_change_day": 30,
                "reputation": 693318,
                "creation_date": 1221842906,
                "user_type": "registered",
                "user_id": 19068,
                "location": "United Kingdom",
                "website_url": "",
                "link": "https://stackoverflow.com/users/19068/quentin",
                "profile_image": "https://www.gravatar.com/avatar/1d2d3229ed1961d2bd81853242493247?s=128&d=identicon&r=PG",
                "display_name": "Quentin"
            },
            {
                "badge_counts": {
                    "bronze": 1728,
                    "silver": 1341,
                    "gold": 188
                },
                "account_id": 8291,
                "is_employee": false,
                "last_modified_date": 1571976027,
                "last_access_date": 1572154564,
                "reputation_change_year": 45651,
                "reputation_change_quarter": 4328,
                "reputation_change_month": 4328,
                "reputation_change_week": 155,
                "reputation_change_day": 155,
                "reputation": 673426,
                "creation_date": 1221622605,
                "user_type": "registered",
                "user_id": 14860,
                "accept_rate": 100,
                "website_url": "",
                "link": "https://stackoverflow.com/users/14860/paxdiablo",
                "profile_image": "https://i.stack.imgur.com/vXG1F.png?s=128&g=1",
                "display_name": "paxdiablo"
            },
            {
                "badge_counts": {
                    "bronze": 1297,
                    "silver": 1070,
                    "gold": 136
                },
                "account_id": 34048,
                "is_employee": false,
                "last_modified_date": 1571128221,
                "last_access_date": 1572021884,
                "reputation_change_year": 50061,
                "reputation_change_quarter": 4414,
                "reputation_change_month": 4414,
                "reputation_change_week": 20,
                "reputation_change_day": 20,
                "reputation": 668335,
                "creation_date": 1240625354,
                "user_type": "registered",
                "user_id": 95810,
                "accept_rate": 80,
                "location": "Sunnyvale, CA",
                "website_url": "http://www.aleax.it",
                "link": "https://stackoverflow.com/users/95810/alex-martelli",
                "profile_image": "https://www.gravatar.com/avatar/e8d5fe90f1fe2148bf130cccd4dc311c?s=128&d=identicon&r=PG",
                "display_name": "Alex Martelli"
            },
            {
                "badge_counts": {
                    "bronze": 819,
                    "silver": 864,
                    "gold": 167
                },
                "account_id": 3748,
                "is_employee": false,
                "last_modified_date": 1570655123,
                "last_access_date": 1572108920,
                "reputation_change_year": 48005,
                "reputation_change_quarter": 4160,
                "reputation_change_month": 4160,
                "reputation_change_week": 20,
                "reputation_change_day": 20,
                "reputation": 634955,
                "creation_date": 1220976258,
                "user_type": "registered",
                "user_id": 5445,
                "location": "Guatemala",
                "website_url": "http://codingspot.com",
                "link": "https://stackoverflow.com/users/5445/cms",
                "profile_image": "https://www.gravatar.com/avatar/932fb89b9d4049cec5cba357bf0ae388?s=128&d=identicon&r=PG",
                "display_name": "CMS"
            },
            {
                "badge_counts": {
                    "bronze": 1268,
                    "silver": 859,
                    "gold": 65
                },
                "account_id": 134022,
                "is_employee": false,
                "last_modified_date": 1571936700,
                "last_access_date": 1572148672,
                "reputation_change_year": 23488,
                "reputation_change_quarter": 1915,
                "reputation_change_month": 1915,
                "reputation_change_week": 30,
                "reputation_change_day": 30,
                "reputation": 633374,
                "creation_date": 1273269250,
                "user_type": "registered",
                "user_id": 335858,
                "accept_rate": 81,
                "location": "United States",
                "website_url": "http://stackoverflow.com/users/335858/dasblinkenlight",
                "link": "https://stackoverflow.com/users/335858/dasblinkenlight",
                "profile_image": "https://www.gravatar.com/avatar/4af3541c00d591e9a518b9c0b3b1190a?s=128&d=identicon&r=PG",
                "display_name": "dasblinkenlight"
            },
            {
                "badge_counts": {
                    "bronze": 1361,
                    "silver": 1412,
                    "gold": 140
                },
                "account_id": 24377,
                "is_employee": false,
                "last_modified_date": 1571043917,
                "last_access_date": 1571913014,
                "reputation_change_year": 47182,
                "reputation_change_quarter": 4100,
                "reputation_change_month": 4100,
                "reputation_change_week": 10,
                "reputation_change_day": 10,
                "reputation": 630408,
                "creation_date": 1233672960,
                "user_type": "registered",
                "user_id": 61974,
                "location": "Denmark",
                "website_url": "http://careers.stackoverflow.com/markbyers/",
                "link": "https://stackoverflow.com/users/61974/mark-byers",
                "profile_image": "https://www.gravatar.com/avatar/ad240ed5cc406759f0fd72591dc8ca47?s=128&d=identicon&r=PG",
                "display_name": "Mark Byers"
            },
            {
                "badge_counts": {
                    "bronze": 1205,
                    "silver": 1117,
                    "gold": 113
                },
                "account_id": 10930,
                "is_employee": false,
                "last_modified_date": 1572051632,
                "last_access_date": 1546328601,
                "reputation_change_year": 43560,
                "reputation_change_quarter": 3747,
                "reputation_change_month": 3747,
                "reputation_change_week": 10,
                "reputation_change_day": 10,
                "reputation": 619790,
                "creation_date": 1222135580,
                "user_type": "registered",
                "user_id": 20862,
                "accept_rate": 50,
                "website_url": "",
                "link": "https://stackoverflow.com/users/20862/ignacio-vazquez-abrams",
                "profile_image": "https://www.gravatar.com/avatar/2343ae368d3241278581ce6c87f62a25?s=128&d=identicon&r=PG",
                "display_name": "Ignacio Vazquez-Abrams"
            },
            {
                "badge_counts": {
                    "bronze": 1299,
                    "silver": 1166,
                    "gold": 138
                },
                "account_id": 7633,
                "is_employee": false,
                "last_modified_date": 1572095109,
                "last_access_date": 1572158177,
                "reputation_change_year": 38253,
                "reputation_change_quarter": 2909,
                "reputation_change_month": 2909,
                "reputation_change_week": 0,
                "reputation_change_day": 0,
                "reputation": 608745,
                "creation_date": 1221588555,
                "user_type": "registered",
                "user_id": 13302,
                "accept_rate": 99,
                "location": "Bern, Switzerland",
                "website_url": "",
                "link": "https://stackoverflow.com/users/13302/marc-s",
                "profile_image": "https://www.gravatar.com/avatar/b4779212f57ff2e9549ea90a4499c2d7?s=128&d=identicon&r=PG",
                "display_name": "marc_s"
            },
            {
                "badge_counts": {
                    "bronze": 1371,
                    "silver": 1116,
                    "gold": 127
                },
                "account_id": 11948,
                "is_employee": false,
                "last_modified_date": 1571151900,
                "last_access_date": 1572114594,
                "reputation_change_year": 39819,
                "reputation_change_quarter": 3258,
                "reputation_change_month": 3258,
                "reputation_change_week": 40,
                "reputation_change_day": 40,
                "reputation": 608038,
                "creation_date": 1222642783,
                "user_type": "registered",
                "user_id": 23283,
                "accept_rate": 100,
                "location": "Redmond, WA",
                "website_url": "http://blog.paranoidcoding.com/",
                "link": "https://stackoverflow.com/users/23283/jaredpar",
                "profile_image": "https://www.gravatar.com/avatar/529ba429a58902bef56c2fcb672d5ccb?s=128&d=identicon&r=PG",
                "display_name": "JaredPar"
            },
            {
                "badge_counts": {
                    "bronze": 1341,
                    "silver": 1308,
                    "gold": 115
                },
                "account_id": 64585,
                "is_employee": false,
                "last_modified_date": 1571053802,
                "last_access_date": 1572083448,
                "reputation_change_year": 57891,
                "reputation_change_quarter": 4855,
                "reputation_change_month": 4855,
                "reputation_change_week": 30,
                "reputation_change_day": 30,
                "reputation": 600189,
                "creation_date": 1255610900,
                "user_type": "registered",
                "user_id": 190597,
                "accept_rate": 88,
                "website_url": "",
                "link": "https://stackoverflow.com/users/190597/unutbu",
                "profile_image": "https://www.gravatar.com/avatar/aabc98d5c6482ca0e1405ec97710f30a?s=128&d=identicon&r=PG&f=1",
                "display_name": "unutbu"
            },
            {
                "badge_counts": {
                    "bronze": 1084,
                    "silver": 723,
                    "gold": 100
                },
                "account_id": 8423,
                "is_employee": false,
                "last_modified_date": 1571418312,
                "last_access_date": 1572157633,
                "reputation_change_year": 38937,
                "reputation_change_quarter": 3301,
                "reputation_change_month": 3301,
                "reputation_change_week": 0,
                "reputation_change_day": 0,
                "reputation": 598977,
                "creation_date": 1221633947,
                "user_type": "registered",
                "user_id": 15168,
                "accept_rate": 100,
                "location": "California, USA",
                "website_url": "https://stackoverflow.com/users/15168",
                "link": "https://stackoverflow.com/users/15168/jonathan-leffler",
                "profile_image": "https://i.stack.imgur.com/WtEI9.png?s=128&g=1",
                "display_name": "Jonathan Leffler"
            },
            {
                "badge_counts": {
                    "bronze": 975,
                    "silver": 912,
                    "gold": 137
                },
                "account_id": 76141,
                "is_employee": false,
                "last_modified_date": 1571791807,
                "last_access_date": 1572082895,
                "reputation_change_year": 52220,
                "reputation_change_quarter": 4310,
                "reputation_change_month": 4310,
                "reputation_change_week": 5,
                "reputation_change_day": 5,
                "reputation": 596904,
                "creation_date": 1259104089,
                "user_type": "registered",
                "user_id": 218196,
                "accept_rate": 100,
                "website_url": "http://felix-kling.de",
                "link": "https://stackoverflow.com/users/218196/felix-kling",
                "profile_image": "https://i.stack.imgur.com/4P5DY.jpg?s=128&g=1",
                "display_name": "Felix Kling"
            },
            {
                "badge_counts": {
                    "bronze": 900,
                    "silver": 606,
                    "gold": 84
                },
                "account_id": 26521,
                "is_employee": false,
                "last_modified_date": 1571763912,
                "last_access_date": 1571226609,
                "reputation_change_year": 32294,
                "reputation_change_quarter": 2352,
                "reputation_change_month": 2352,
                "reputation_change_week": 0,
                "reputation_change_day": 0,
                "reputation": 584496,
                "creation_date": 1235161492,
                "user_type": "registered",
                "user_id": 69083,
                "location": "Virsbo, Sweden",
                "website_url": "http://www.guffa.com",
                "link": "https://stackoverflow.com/users/69083/guffa",
                "profile_image": "https://www.gravatar.com/avatar/1db0cdfd3fe268e270ec481a73046c2f?s=128&d=identicon&r=PG",
                "display_name": "Guffa"
            },
            {
                "badge_counts": {
                    "bronze": 1069,
                    "silver": 963,
                    "gold": 70
                },
                "account_id": 277416,
                "is_employee": false,
                "last_modified_date": 1572122107,
                "last_access_date": 1572125157,
                "reputation_change_year": 40186,
                "reputation_change_quarter": 3307,
                "reputation_change_month": 3307,
                "reputation_change_week": 0,
                "reputation_change_day": 0,
                "reputation": 574687,
                "creation_date": 1294757277,
                "user_type": "registered",
                "user_id": 571407,
                "accept_rate": 100,
                "location": "Saint-Etienne, France",
                "website_url": "",
                "link": "https://stackoverflow.com/users/571407/jb-nizet",
                "profile_image": "https://www.gravatar.com/avatar/2f0d9dec16bae1e06552af55ddefc11f?s=128&d=identicon&r=PG",
                "display_name": "JB Nizet"
            },
            {
                "badge_counts": {
                    "bronze": 1975,
                    "silver": 1105,
                    "gold": 153
                },
                "account_id": 32093,
                "is_employee": false,
                "last_modified_date": 1571537418,
                "last_access_date": 1572147360,
                "reputation_change_year": 33356,
                "reputation_change_quarter": 2566,
                "reputation_change_month": 2566,
                "reputation_change_week": 0,
                "reputation_change_day": 0,
                "reputation": 568098,
                "creation_date": 1239204526,
                "user_type": "registered",
                "user_id": 88656,
                "location": "Seattle, WA",
                "website_url": "http://ericlippert.com",
                "link": "https://stackoverflow.com/users/88656/eric-lippert",
                "profile_image": "https://www.gravatar.com/avatar/6fbdff3ffb6f111d172759b4f05bea0e?s=128&d=identicon&r=PG",
                "display_name": "Eric Lippert"
            },
            {
                "badge_counts": {
                    "bronze": 440,
                    "silver": 364,
                    "gold": 49
                },
                "account_id": 262968,
                "is_employee": false,
                "last_modified_date": 1571187917,
                "last_access_date": 1572143933,
                "reputation_change_year": 42326,
                "reputation_change_quarter": 4025,
                "reputation_change_month": 4025,
                "reputation_change_week": 0,
                "reputation_change_day": 0,
                "reputation": 562453,
                "creation_date": 1292821840,
                "user_type": "registered",
                "user_id": 548225,
                "accept_rate": 90,
                "location": "Bangalore, India",
                "website_url": "http://anubhava.wordpress.com",
                "link": "https://stackoverflow.com/users/548225/anubhava",
                "profile_image": "https://www.gravatar.com/avatar/dab08478b226280d4a30894c9a7ed719?s=128&d=identicon&r=PG",
                "display_name": "anubhava"
            },
            {
                "badge_counts": {
                    "bronze": 617,
                    "silver": 573,
                    "gold": 84
                },
                "account_id": 10375,
                "is_employee": false,
                "last_modified_date": 1571238321,
                "last_access_date": 1571992060,
                "reputation_change_year": 47720,
                "reputation_change_quarter": 4285,
                "reputation_change_month": 4285,
                "reputation_change_week": 20,
                "reputation_change_day": 20,
                "reputation": 555856,
                "creation_date": 1221903545,
                "user_type": "registered",
                "user_id": 19563,
                "location": "United Kingdom",
                "website_url": "",
                "link": "https://stackoverflow.com/users/19563/cb-bailey",
                "profile_image": "https://www.gravatar.com/avatar/a8db27c91db97757a829c7971fd62b84?s=128&d=identicon&r=PG",
                "display_name": "CB Bailey"
            },
            {
                "badge_counts": {
                    "bronze": 1238,
                    "silver": 1215,
                    "gold": 134
                },
                "account_id": 37175,
                "is_employee": false,
                "last_modified_date": 1572123907,
                "last_access_date": 1571830758,
                "reputation_change_year": 40756,
                "reputation_change_quarter": 3295,
                "reputation_change_month": 3295,
                "reputation_change_week": 10,
                "reputation_change_day": 10,
                "reputation": 555589,
                "creation_date": 1242214829,
                "user_type": "moderator",
                "user_id": 106224,
                "accept_rate": 96,
                "location": "Singapore",
                "website_url": "https://NOVALISTIC.com",
                "link": "https://stackoverflow.com/users/106224/boltclock",
                "profile_image": "https://www.gravatar.com/avatar/a2d818d801ce38a33807f68fdd92043a?s=128&d=identicon&r=PG",
                "display_name": "BoltClock"
            }
        ],
        "has_more": true,
        "quota_max": 300,
        "quota_remaining": 282
    }
}